core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views


from . import views

app_name = "core"

urlpatterns = [
    path(r"", views.HomeView.as_view(), name="home"),
    path(r"dashboard", views.DashboardView.as_view(), name="dashboard"),
    path(
        r"dashboard/course/create",
        views.CourseCreateView.as_view(),
        name="course_create",
    ),
    path(
        r"dashboard/course/edit/<int:pk>",
        views.CourseUpdateView.as_view(),
        name="course_edit",
    ),
    path(
        r"dashboard/course/delete/<int:pk>",
        views.CourseDeleteView.as_view(),
        name="course_delete",
    ),
    path(r"dashboard/course", views.CourseListView.as_view(), name="course_list"),
    path(
        r"dashboard/admission/create",
        views.AdmissionPeriodeCreateView.as_view(),
        name="admission_create",
    ),
    path(
        r"dashboard/admission/edit/<int:pk>",
        views.AdmissionPeriodeUpdateView.as_view(),
        name="admission_edit",
    ),
    path(
        r"dashboard/admission/delete/<int:pk>",
        views.AdmissionPeriodeDeleteView.as_view(),
        name="admission_delete",
    ),
    path(
        r"dashboard/applicant",
        views.ApplicantListView.as_view(),
        name="applicant_list",
    ),
    path(
        r"dashboard/applicant/<uuid:ref>",
        views.ApplicantDetailView.as_view(),
        name="applicant_detail",
    ),
    path(
        r"dashboard/admission",
        views.AdmissionPeriodListView.as_view(),
        name="admission_list",
    ),
    path(r"apply", views.ApplyFirstCreateView.as_view(), name="apply"),
    path(r"apply2/<uuid:ref>", views.ApplySecondCreateView.as_view(), name="apply2"),
    path(r"apply3/<uuid:ref>", views.ApplyThirdCreateView.as_view(), name="apply3"),
    path(r"apply4/<int:res>", views.ApplyFourthCreateView.as_view(), name="apply4"),
    path(r"check_status", views.CheckStatusFormView.as_view(), name="check_status"),
    path(
        r"admission_status/<str:email>",
        views.AdmissionStatusDetailView.as_view(),
        name="admission_status",
    ),
    #     path(r"form/list", views.ApplicationListView.as_view(), name="list_applicants"),
    #     path(
    #         r"form/<uuid:ref>/",
    #         views.ApplicationDetailView.as_view(),
    #         name="submitted_form",
    #     ),
    #     path(
    #         r"form/<uuid:ref>/process", views.ApplicationAdmitView.as_view(), name="process"
    #     ),
    path(r"accounts/login/", auth_views.LoginView.as_view(), name="login"),
]

eadmission/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(r'', include('core.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

User = get_user_model()


class Course(models.Model):
    FACULTY = [
        ("NAS", "Natural and Applied Science"),
        ("MSS", "Management and Social Science"),
    ]
    title = models.CharField(max_length=25)
    faculty = models.CharField(max_length=25, choices=FACULTY)

    def __str__(self):
        return self.title


class Application(models.Model):
    GENDER = [("Male", "Male"), ("Female", "Female")]
    MARRITAL_STATUS = [("Single", "Single"), ("Married", "Married")]
    DEGREE = [
        ("Bachelor's", "Bachelor's"),
        ("Master's", "Master's"),
        ("PHD/PG", "PHD/PG"),
    ]
    STATUS = [
        ("Review", "Under Review"),
        ("Granted", "Admission Granted"),
        ("Denied", "Admission Denied"),
    ]

    EXAM_TYPE = [("WAEC", "WAEC"), ("NECO", "NECO")]

    # Personal Dat
    ref = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    middle_name = models.CharField(max_length=25)
    gender = models.CharField(max_length=25, choices=GENDER)
    date_of_birth = models.DateField()
    marrital_status = models.CharField(max_length=25, choices=MARRITAL_STATUS)
    address = models.CharField(max_length=50)
    email = models.EmailField(max_length=25, unique=True)
    phone = models.CharField(max_length=25)
    nationality = models.CharField(max_length=25)
    state_of_origin = models.CharField(max_length=25)
    local_government = models.CharField(max_length=25)
    # attatchments
    attatched_passport = models.ImageField()
    # attatched_result = models.FileField()
    # course details
    degree = models.CharField(max_length=25, choices=DEGREE)
    program = models.OneToOneField(Course, on_delete=models.CASCADE)
    status = models.CharField(max_length=25, choices=STATUS, default="Review")

    def get_absolute_url(self):
        return reverse("core:submitted_form", kwargs={"ref": self.ref})

    def get_full_name(self):
        return self.last_name + " " + self.first_name + " " + self.middle_name


class AdmissionPeriod(models.Model):
    title = models.CharField(max_length=25)
    staff = models.OneToOneField(User, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return self.title


class WAEC(models.Model):
    applicant = models.OneToOneField(
        Application, on_delete=models.CASCADE, related_name="waec"
    )
    candidate_number = models.CharField(max_length=25)
    year = models.IntegerField()
    center_number = models.CharField(max_length=25)


class Result(models.Model):
    GRADE = [
        ("A1", "A1"),
        ("B2", "B2"),
        ("B3", "B3"),
        ("C4", "C4"),
        ("C5", "C5"),
        ("C6", "C6"),
        ("D7", "D7"),
        ("E8", "E8"),
        ("F9", "F9"),
    ]
    waec = models.OneToOneField(WAEC, on_delete=models.CASCADE)
    subject_1 = models.CharField(max_length=50,)
    grade_1 = models.CharField(max_length=2, choices=GRADE)
    subject_2 = models.CharField(max_length=50)
    grade_2 = models.CharField(max_length=2, choices=GRADE)
    subject_3 = models.CharField(max_length=50)
    grade_3 = models.CharField(max_length=2, choices=GRADE)
    subject_4 = models.CharField(max_length=50)
    grade_4 = models.CharField(max_length=2, choices=GRADE)
    subject_5 = models.CharField(max_length=50)
    grade_5 = models.CharField(max_length=2, choices=GRADE)
    subject_6 = models.CharField(max_length=50)
    grade_6 = models.CharField(max_length=2, choices=GRADE)
    subject_7 = models.CharField(max_length=50)
    grade_7 = models.CharField(max_length=2, choices=GRADE)
    subject_8 = models.CharField(max_length=50, blank=True)
    grade_8 = models.CharField(max_length=2, choices=GRADE, blank=True)
    subject_9 = models.CharField(max_length=50, blank=True)
    grade_9 = models.CharField(max_length=2, choices=GRADE, blank=True)


class JAMB(models.Model):
    applicant = models.OneToOneField(
        Application, on_delete=models.CASCADE, related_name="jamb"
    )
    year = models.IntegerField()
    score = models.IntegerField()

    def __str__(self):
        return str(self.score)

core/forms.py
from django import forms

from .models import AdmissionPeriod, Application, WAEC, JAMB, Result


class AdmissionPeriodCreateForm(forms.ModelForm):
    start_date = forms.DateField(widget=forms.TextInput(attrs={"type": "date"}))
    end_date = forms.DateField(widget=forms.TextInput(attrs={"type": "date"}))

    class Meta:
        model = AdmissionPeriod
        fields = ("title", "start_date", "end_date")


class ApplicationCreateForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=forms.TextInput(attrs={"type": "date"}))

    class Meta:
        model = Application
        fields = fields = [
            "first_name",
            "last_name",
            "middle_name",
            "gender",
            "date_of_birth",
            "marrital_status",
            "address",
            "email",
            "phone",
            "nationality",
            "state_of_origin",
            "local_government",
            "attatched_passport",
            "degree",
            "program",
        ]


class WAECCreateForm(forms.ModelForm):
    class Meta:
        model = WAEC
        fields = ["candidate_number", "center_number", "year", "applicant"]
        widgets = {"applicant": forms.HiddenInput()}


class JAMBCreateForm(forms.ModelForm):
    class Meta:
        model = JAMB
        fields = ["score", "year", "applicant"]
        widgets = {"applicant": forms.HiddenInput()}


class StatusForm(forms.Form):
    email = forms.EmailField()

    class Meta:
        fields = ["email"]


class ResultCreateForm(forms.ModelForm):
    class Meta:
        model = Result
        fields = [
            "waec",
            "subject_1",
            "grade_1",
            "subject_2",
            "grade_2",
            "subject_3",
            "grade_3",
            "subject_4",
            "grade_4",
            "subject_5",
            "grade_5",
            "subject_6",
            "grade_6",
            "subject_7",
            "grade_7",
            "subject_8",
            "grade_8",
            "subject_9",
            "grade_9",
        ]
        widgets = {"waec": forms.HiddenInput()}

core/views.py
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    RedirectView,
    UpdateView,
    DeleteView,
    FormView,
)
from extra_views import CreateWithInlinesView, InlineFormSetFactory

from core.models import Application, Course, AdmissionPeriod, WAEC
from core.forms import (
    AdmissionPeriodCreateForm,
    ApplicationCreateForm,
    WAECCreateForm,
    JAMBCreateForm,
    ResultCreateForm,
    StatusForm,
)


class HomeView(TemplateView):
    template_name = "core/index.html"


class ApplyFirstCreateView(CreateView):
    form_class = ApplicationCreateForm
    template_name = "core/apply/page1.html"

    def get_success_url(self):
        return reverse("core:apply2", kwargs={"ref": self.object.ref})


class ApplySecondCreateView(CreateView):
    form_class = JAMBCreateForm
    template_name = "core/apply/page2.html"

    def get_initial(self):
        appl = get_object_or_404(Application, ref=self.kwargs.get("ref"))
        return {"applicant": appl}

    def get_success_url(self):
        return reverse("core:apply3", kwargs={"ref": self.request.POST["applicant"]})


class ApplyThirdCreateView(CreateView):
    form_class = WAECCreateForm
    template_name = "core/apply/page3.html"

    def get_initial(self):
        appl = get_object_or_404(Application, ref=self.kwargs.get("ref"))
        return {"applicant": appl}

    def get_success_url(self):
        return reverse("core:apply4", kwargs={"res": self.object.id})


class ApplyFourthCreateView(CreateView):
    form_class = ResultCreateForm
    template_name = "core/apply/page4.html"
    success_url = reverse_lazy("core:home")

    def get_initial(self):
        waec = get_object_or_404(WAEC, id=self.kwargs.get("res"))
        return {"waec": waec}


class CheckStatusFormView(FormView):
    form_class = StatusForm
    template_name = "core/status/form.html"

    def get_success_url(self):
        return reverse_lazy(
            "core:admission_status", kwargs={"email": self.request.POST["email"]}
        )


class AdmissionStatusDetailView(DetailView):
    model = Application
    slug_field = "email"
    slug_url_kwarg = "email"
    template_name = "core/status/detail.html"

    def get_queryset(self):
        return Application.objects.filter(email=self.kwargs.get("email"))


class ApplicationListView(LoginRequiredMixin, ListView):
    model = Application
    template_name = "core/list.html"
    context_object_name = "application_forms"


class ApplicationDetailView(DetailView):
    pk_url_kwarg = "ref"
    model = Application
    template_name = "core/detail.html"
    context_object_name = "form"


class StatusRedirectView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy(
            "core:submitted_form", kwargs={"ref": self.request.GET.get("ref")}
        )


class ApplicationAdmitView(LoginRequiredMixin, UpdateView):
    model = Application
    pk_url_kwarg = "ref"
    fields = ["status"]

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy(
            "core:submitted_form", kwargs={"ref": self.kwargs.get("ref")}
        )


class DashboardView(ListView):
    model = Application
    template_name = "core/dashboard/index.html"


class CourseCreateView(LoginRequiredMixin, CreateView):
    model = Course
    template_name = "core/dashboard/course/create.html"
    success_url = reverse_lazy("core:course_list")
    fields = ["title", "faculty"]


class CourseUpdateView(LoginRequiredMixin, UpdateView):
    model = Course
    template_name = "core/dashboard/course/edit.html"
    success_url = reverse_lazy("core:course_list")
    fields = ["title", "faculty"]


class CourseDeleteView(LoginRequiredMixin, DeleteView):
    model = Course
    template_name = "core/dashboard/course/delete.html"
    success_url = reverse_lazy("core:course_list")


class CourseListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = "core/dashboard/course/list.html"


class AdmissionPeriodeCreateView(LoginRequiredMixin, CreateView):
    form_class = AdmissionPeriodCreateForm
    template_name = "core/dashboard/admissions/create.html"
    success_url = reverse_lazy("core:admission_list")

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.staff = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class AdmissionPeriodListView(LoginRequiredMixin, ListView):
    model = AdmissionPeriod
    context_object_name = "admission_period_list"
    template_name = "core/dashboard/admissions/list.html"


class AdmissionPeriodeUpdateView(LoginRequiredMixin, UpdateView):
    form_class = AdmissionPeriodCreateForm
    model = AdmissionPeriod
    template_name = "core/dashboard/admissions/edit.html"
    success_url = reverse_lazy("core:admission_list")


class AdmissionPeriodeDeleteView(LoginRequiredMixin, DeleteView):
    model = AdmissionPeriod
    template_name = "core/dashboard/admissions/delete.html"
    success_url = reverse_lazy("core:admission_list")


class ApplicantListView(LoginRequiredMixin, ListView):
    model = Application
    template_name = "core/dashboard/applicants/list.html"


class ApplicantDetailView(LoginRequiredMixin, UpdateView):
    model = Application
    slug_field = "ref"
    slug_url_kwarg = "ref"
    fields = ["status"]
    template_name = "core/dashboard/applicants/detail.html"
    success_url = reverse_lazy("core:applicant_list")

core/templates/core/index.html
{% extends 'core/public_base.html' %}

{% load static %}

{% block content %}
<!-- Hero section -->
<section class="hero-section">
    <div class="hero-slider owl-carousel">
        <div class="hs-item set-bg" data-setbg="{% static 'public/img/hero-slider/1.jpg' %}">
            <div class="hs-text">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="hs-subtitle">Award Winning UNIVERSITY</div>
                            <h2 class="hs-title">Make Godfrey Okoye University your first choice</h2>
                            <p class="hs-des">2020/2021 Admission in progress</p>
                            <a href="{% url 'core:apply' %}" class="site-btn text-white">APPLY NOW</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="hs-item set-bg" data-setbg="{% static 'public/img/hero-slider/2.jpg' %}">
            <div class="hs-text">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="hs-subtitle">Award Winning UNIVERSITY</div>
                            <h2 class="hs-title">Gouni Online Learning.</h2>
                            <p class="hs-des">
                                Actionable. Engaging. Interactive</p>
                            <a href="{% url 'core:apply' %}" class="site-btn text-white">APPLY NOW</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Hero section end -->



<!-- Services section -->
<section class="service-section spad">
    <div class="container services">
        <div class="section-title text-center">
            <h3>OUR FACULTIES</h3>
            <p>We provides the opportunity to prepare for life</p>
        </div>
        <div class="row">
            <div class="col-lg-4 col-sm-6 service-item">
                <div class="service-icon">
                    <img src="{% static 'public/img/services-icons/1.png' %}" alt="1">
                </div>
                <div class="service-content">
                    <h4>Art</h4>
                    <p>Faculty of Arts is the youngest faculty in Godfrey Okoye University. We started in 2014.</p>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6 service-item">
                <div class="service-icon">
                    <img src="{% static 'public/img/services-icons/2.png' %}" alt="1">
                </div>
                <div class="service-content">
                    <h4>Management and social Sciences</h4>
                    <p>GOODWILL MESSAGE TO STUDENTS It is my singular privilege and honour to convey my maiden message
                        of goodwill to our beloved students of Godfrey Okoye University, Enugu</p>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6 service-item">
                <div class="service-icon">
                    <img src="{% static 'public/img/services-icons/3.png' %}" alt="1">
                </div>
                <div class="service-content">
                    <h4>Education</h4>
                    <p>According to Okafor (2012) the concept of University varies widely from country to country and
                        sometimes varies even within the same country. </p>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6 service-item">
                <div class="service-icon">
                    <img src="{% static 'public/img/services-icons/4.png' %}" alt="1">
                </div>
                <div class="service-content">
                    <h4>Law</h4>
                    <p>On behalf of the Vice-Chancellor, Rev. Fr. Prof. Dr. Christian Anieke, Management and Staff of
                        Godfrey Okoye University, I warmly welcome all our old and incoming students to our Faculty of
                        Law.</p>
                </div>
            </div>

            <div class="col-lg-4 col-sm-6 service-item">
                <div class="service-icon">
                    <img src="{% static 'public/img/services-icons/6.png' %}" alt="1">
                </div>
                <div class="service-content">
                    <h4>Natural and Applied Sciences</h4>
                    <p>Welcome to Godfrey Okoye University’s Faculty of Natural and Applied Sciences </p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Services section end -->


<!-- Enroll section -->
<section class="enroll-section spad set-bg" data-setbg="{% static 'public/img/enroll-bg.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-5">
                <div class="section-title text-white">
                    <h3>ENROLLMENT</h3>
                    <p>Get started with us to explore the exciting</p>
                </div>
                <div class="enroll-list text-white">
                    <div class="enroll-list-item">
                        <span>1</span>
                        <h5>Requrements</h5>
                        <p>O’Level Result: 5 credits in the required subjects of the chosen course of study, including
                            English and Mathematics.</p>
                    </div>
                    <div class="enroll-list-item">
                        <span>2</span>
                        <h5>Apply</h5>
                        <p>Apply online – On submitting the form, a reply will be sent to the candidates email address
                        </p>
                    </div>
                    <div class="enroll-list-item">
                        <span>3</span>
                        <h5>Pay Fees</h5>
                        <p>The candidate can start paying fees after receiving admission lette</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 offset-lg-1 p-lg-0 p-4">
                <img src="{% static 'public/img/encroll-img.jpg' %}" alt="">
            </div>
        </div>
    </div>
</section>
<!-- Enroll section end -->


<!-- Courses section -->
<section class="courses-section spad">
    <div class="container">
        <div class="section-title text-center">
            <h3>OUR COURSES</h3>
            <p>Building a better world, one course at a time</p>
        </div>
        <div class="row">
            <!-- course item -->
            <div class="col-lg-4 col-md-6 course-item">
                <div class="course-thumb">
                    <img src="{% static 'public/img/course/1.jpg' %}" alt="">
                    <div class="course-cat">
                        <span>COMPUTER SCIENCE </span>
                    </div>
                </div>

            </div>
            <!-- course item -->
            <div class="col-lg-4 col-md-6 course-item">
                <div class="course-thumb">
                    <img src="{% static 'public/img/course/2.jpg' %}" alt="">
                    <div class="course-cat">
                        <span>LAW</span>
                    </div>
                </div>

            </div>
            <!-- course item -->
            <div class="col-lg-4 col-md-6 course-item">
                <div class="course-thumb">
                    <img src="{% static 'public/img/course/3.jpg' %}" alt="">
                    <div class="course-cat">
                        <span>CHEMISTRY</span>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- Courses section end-->


<!-- Fact section -->
<section class="fact-section spad set-bg" data-setbg="{% static 'public/img/fact-bg.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-lg-3 fact">
                <div class="fact-icon">
                    <i class="ti-crown"></i>
                </div>
                <div class="fact-text">
                    <h2>10</h2>
                    <p>YEARS</p>
                </div>
            </div>
            <div class="col-sm-6 col-lg-3 fact">
                <div class="fact-icon">
                    <i class="ti-briefcase"></i>
                </div>
                <div class="fact-text">
                    <h2>80</h2>
                    <p>TEACHERS</p>
                </div>
            </div>
            <div class="col-sm-6 col-lg-3 fact">
                <div class="fact-icon">
                    <i class="ti-user"></i>
                </div>
                <div class="fact-text">
                    <h2>4000</h2>
                    <p>STUDENTS</p>
                </div>
            </div>
            <div class="col-sm-6 col-lg-3 fact">
                <div class="fact-icon">
                    <i class="ti-pencil-alt"></i>
                </div>
                <div class="fact-text">
                    <h2>30+</h2>
                    <p>Programs</p>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

core/templates/core/public_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Godfrey Okoye University</title>
    <meta charset="UTF-8">
    <meta name="description" content="Unica University Template">
    <meta name="keywords" content="event, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Favicon -->
    <link href="{% static 'public/img/favicon.ico' %}" rel="shortcut icon" />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,400i,500,500i,700,700i" rel="stylesheet">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="{% static 'public/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'public/css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'public/img/css/themify-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'public/css/magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'public/css/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'public/css/owl.carousel.css' %}" />
    <link rel="stylesheet" href="{% static 'public/css/style.css' %}" />


    <!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- header section -->
    <header class="header-section">
        <div class="container">
            <!-- logo -->
            <a href="/"><img src="{% static '/img/GOU_logo.jpg' %}" style="max-height: 50px;"></a>
            <div class="nav-switch">
                <i class="fa fa-bars"></i>
            </div>
            <div class="header-info">
                <div class="hf-item">
                    <i class="fa fa-clock-o"></i>
                    <p><span>Working time:</span>Monday - Friday: 08 AM - 06 PM</p>
                </div>
                <div class="hf-item">
                    <i class="fa fa-map-marker"></i>
                    <p><span>Find us:</span>Jideofor St, Thinkers Corner 400001, Enugu</p>
                </div>
            </div>
        </div>
    </header>
    <!-- header section end-->


    <!-- Header section  -->
    <nav class="nav-section bg-primary">
        <div class="container">

            <ul class="main-menu">
                <li class="active"><a href="{% url 'core:home' %}">Home</a></li>
                <li><a href="{% url 'core:check_status' %}">Admission Status</a></li>
                <li><a href="{% url 'core:apply' %}">Apply</a></li>
            </ul>
        </div>
    </nav>
    <!-- Header section end -->


    {% block content %}

    {% endblock content %}



    <!-- Footer section -->
    <footer class="footer-section bg-primary">
        <div class="container footer-top">
            <div class="row">
                <!-- widget -->
                <div class="col-sm-6 col-lg-3 footer-widget">
                    <div class="about-widget">
                        <img src="{% static 'img/GOU_logo.jpg' %}" style="max-height: 50px;" />
                        <p>GO University received its operational licence from the National Universities Commission
                            (NUC) in 2009, and so commenced full academic activities in the 2009/2010. All our
                            programmes have NUC accreditation. </p>
                        <div class="social pt-1">
                            <a href=""><i class="fa fa-twitter-square"></i></a>
                            <a href=""><i class="fa fa-facebook-square"></i></a>
                            <a href=""><i class="fa fa-google-plus-square"></i></a>
                            <a href=""><i class="fa fa-linkedin-square"></i></a>
                            <a href=""><i class="fa fa-rss-square"></i></a>
                        </div>
                    </div>
                </div>
                <!-- widget -->
                <div class="col-sm-6 col-lg-3 footer-widget">
                    <h6 class="fw-title">USEFUL LINK</h6>
                    <div class="dobule-link">
                        <ul>
                            <li><a href="">Home</a></li>
                            <li><a href="">About us</a></li>
                            <li><a href="">Services</a></li>
                            <li><a href="">Events</a></li>
                            <li><a href="">Features</a></li>
                        </ul>
                        <ul>
                            <li><a href="">Policy</a></li>
                            <li><a href="">Term</a></li>
                            <li><a href="">Help</a></li>
                            <li><a href="">FAQs</a></li>
                            <li><a href="">Site map</a></li>
                        </ul>
                    </div>
                </div>
                <!-- widget -->
                <div class="col-sm-6 col-lg-3 footer-widget">
                    <h6 class="fw-title">RECENT POST</h6>
                    <ul class="recent-post">
                        <li>
                            <p>Snackable study:How to break <br> up your master's degree</p>
                            <span><i class="fa fa-clock-o"></i>24 Mar 2018</span>
                        </li>
                        <li>
                            <p>Open University plans major <br> cuts to number of staff</p>
                            <span><i class="fa fa-clock-o"></i>24 Mar 2018</span>
                        </li>
                    </ul>
                </div>
                <!-- widget -->
                <div class="col-sm-6 col-lg-3 footer-widget">
                    <h6 class="fw-title">CONTACT</h6>
                    <ul class="contact">
                        <li>
                            <p><i class="fa fa-map-marker"></i> Jideofor St, Thinkers Corner 400001, Enugu</p>
                        </li>
                        <li>
                            <p><i class="fa fa-phone"></i> 0806 882 0118</p>
                        </li>
                        <li>
                            <p><i class="fa fa-envelope"></i> info@gouni.edu.ng</p>
                        </li>
                        <li>
                            <p><i class="fa fa-clock-o"></i> Monday - Friday, 08:00AM - 06:00 PM</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </footer>
    <!-- Footer section end-->



    <!--====== Javascripts & Jquery ======-->
    <script src="{% static 'public/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'public/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'public/js/jquery.countdown.js' %}"></script>
    <script src="{% static 'public/js/masonry.pkgd.min.js' %}"></script>
    <script src="{% static 'public/js/magnific-popup.min.js' %}"></script>
    <script src="{% static 'public/js/main.js' %}"></script>

</body>

</html>