core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views


from . import views

app_name = "core"

urlpatterns = [
    path(r"", views.HomeView.as_view(), name="home"),
    path(r"dashboard", views.DashboardView.as_view(), name="dashboard"),
    path(
        r"dashboard/course/create",
        views.CourseCreateView.as_view(),
        name="course_create",
    ),
    path(
        r"dashboard/course/edit/<int:pk>",
        views.CourseUpdateView.as_view(),
        name="course_edit",
    ),
    path(
        r"dashboard/course/delete/<int:pk>",
        views.CourseDeleteView.as_view(),
        name="course_delete",
    ),
    path(r"dashboard/course", views.CourseListView.as_view(), name="course_list"),
    path(
        r"dashboard/admission/create",
        views.AdmissionPeriodeCreateView.as_view(),
        name="admission_create",
    ),
    path(
        r"dashboard/admission/edit/<int:pk>",
        views.AdmissionPeriodeUpdateView.as_view(),
        name="admission_edit",
    ),
    path(
        r"dashboard/admission/delete/<int:pk>",
        views.AdmissionPeriodeDeleteView.as_view(),
        name="admission_delete",
    ),
    path(
        r"dashboard/applicant",
        views.ApplicantListView.as_view(),
        name="applicant_list",
    ),
    path(
        r"dashboard/applicant/<uuid:ref>",
        views.ApplicantDetailView.as_view(),
        name="applicant_detail",
    ),
    path(
        r"dashboard/admission",
        views.AdmissionPeriodListView.as_view(),
        name="admission_list",
    ),
    path(r"apply", views.ApplyFirstCreateView.as_view(), name="apply"),
    path(r"apply2/<uuid:ref>", views.ApplySecondCreateView.as_view(), name="apply2"),
    path(r"apply3/<uuid:ref>", views.ApplyThirdCreateView.as_view(), name="apply3"),
    path(r"apply4/<int:res>", views.ApplyFourthCreateView.as_view(), name="apply4"),
    path(r"check_status", views.CheckStatusFormView.as_view(), name="check_status"),
    path(
        r"admission_status/<str:email>",
        views.AdmissionStatusDetailView.as_view(),
        name="admission_status",
    ),
    #     path(r"form/list", views.ApplicationListView.as_view(), name="list_applicants"),
    #     path(
    #         r"form/<uuid:ref>/",
    #         views.ApplicationDetailView.as_view(),
    #         name="submitted_form",
    #     ),
    #     path(
    #         r"form/<uuid:ref>/process", views.ApplicationAdmitView.as_view(), name="process"
    #     ),
    path(r"accounts/login/", auth_views.LoginView.as_view(), name="login"),
]

eadmission/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(r'', include('core.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

User = get_user_model()


class Course(models.Model):
    FACULTY = [
        ("NAS", "Natural and Applied Science"),
        ("MSS", "Management and Social Science"),
    ]
    title = models.CharField(max_length=25)
    faculty = models.CharField(max_length=25, choices=FACULTY)

    def __str__(self):
        return self.title


class Application(models.Model):
    GENDER = [("Male", "Male"), ("Female", "Female")]
    MARRITAL_STATUS = [("Single", "Single"), ("Married", "Married")]
    DEGREE = [
        ("Bachelor's", "Bachelor's"),
        ("Master's", "Master's"),
        ("PHD/PG", "PHD/PG"),
    ]
    STATUS = [
        ("Review", "Under Review"),
        ("Granted", "Admission Granted"),
        ("Denied", "Admission Denied"),
    ]

    EXAM_TYPE = [("WAEC", "WAEC"), ("NECO", "NECO")]

    # Personal Dat
    ref = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    middle_name = models.CharField(max_length=25)
    gender = models.CharField(max_length=25, choices=GENDER)
    date_of_birth = models.DateField()
    marrital_status = models.CharField(max_length=25, choices=MARRITAL_STATUS)
    address = models.CharField(max_length=50)
    email = models.EmailField(max_length=25, unique=True)
    phone = models.CharField(max_length=25)
    nationality = models.CharField(max_length=25)
    state_of_origin = models.CharField(max_length=25)
    local_government = models.CharField(max_length=25)
    # attatchments
    attatched_passport = models.ImageField()
    # attatched_result = models.FileField()
    # course details
    degree = models.CharField(max_length=25, choices=DEGREE)
    program = models.OneToOneField(Course, on_delete=models.CASCADE)
    status = models.CharField(max_length=25, choices=STATUS, default="Review")

    def get_absolute_url(self):
        return reverse("core:submitted_form", kwargs={"ref": self.ref})

    def get_full_name(self):
        return self.last_name + " " + self.first_name + " " + self.middle_name


class AdmissionPeriod(models.Model):
    title = models.CharField(max_length=25)
    staff = models.OneToOneField(User, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return self.title


class WAEC(models.Model):
    applicant = models.OneToOneField(
        Application, on_delete=models.CASCADE, related_name="waec"
    )
    candidate_number = models.CharField(max_length=25)
    year = models.IntegerField()
    center_number = models.CharField(max_length=25)


class Result(models.Model):
    GRADE = [
        ("A1", "A1"),
        ("B2", "B2"),
        ("B3", "B3"),
        ("C4", "C4"),
        ("C5", "C5"),
        ("C6", "C6"),
        ("D7", "D7"),
        ("E8", "E8"),
        ("F9", "F9"),
    ]
    waec = models.OneToOneField(WAEC, on_delete=models.CASCADE)
    subject_1 = models.CharField(max_length=50,)
    grade_1 = models.CharField(max_length=2, choices=GRADE)
    subject_2 = models.CharField(max_length=50)
    grade_2 = models.CharField(max_length=2, choices=GRADE)
    subject_3 = models.CharField(max_length=50)
    grade_3 = models.CharField(max_length=2, choices=GRADE)
    subject_4 = models.CharField(max_length=50)
    grade_4 = models.CharField(max_length=2, choices=GRADE)
    subject_5 = models.CharField(max_length=50)
    grade_5 = models.CharField(max_length=2, choices=GRADE)
    subject_6 = models.CharField(max_length=50)
    grade_6 = models.CharField(max_length=2, choices=GRADE)
    subject_7 = models.CharField(max_length=50)
    grade_7 = models.CharField(max_length=2, choices=GRADE)
    subject_8 = models.CharField(max_length=50, blank=True)
    grade_8 = models.CharField(max_length=2, choices=GRADE, blank=True)
    subject_9 = models.CharField(max_length=50, blank=True)
    grade_9 = models.CharField(max_length=2, choices=GRADE, blank=True)


class JAMB(models.Model):
    applicant = models.OneToOneField(
        Application, on_delete=models.CASCADE, related_name="jamb"
    )
    year = models.IntegerField()
    score = models.IntegerField()

    def __str__(self):
        return str(self.score)

core/forms.py
from django import forms

from .models import AdmissionPeriod, Application, WAEC, JAMB, Result


class AdmissionPeriodCreateForm(forms.ModelForm):
    start_date = forms.DateField(widget=forms.TextInput(attrs={"type": "date"}))
    end_date = forms.DateField(widget=forms.TextInput(attrs={"type": "date"}))

    class Meta:
        model = AdmissionPeriod
        fields = ("title", "start_date", "end_date")


class ApplicationCreateForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=forms.TextInput(attrs={"type": "date"}))

    class Meta:
        model = Application
        fields = fields = [
            "first_name",
            "last_name",
            "middle_name",
            "gender",
            "date_of_birth",
            "marrital_status",
            "address",
            "email",
            "phone",
            "nationality",
            "state_of_origin",
            "local_government",
            "attatched_passport",
            "degree",
            "program",
        ]


class WAECCreateForm(forms.ModelForm):
    class Meta:
        model = WAEC
        fields = ["candidate_number", "center_number", "year", "applicant"]
        widgets = {"applicant": forms.HiddenInput()}


class JAMBCreateForm(forms.ModelForm):
    class Meta:
        model = JAMB
        fields = ["score", "year", "applicant"]
        widgets = {"applicant": forms.HiddenInput()}


class StatusForm(forms.Form):
    email = forms.EmailField()

    class Meta:
        fields = ["email"]


class ResultCreateForm(forms.ModelForm):
    class Meta:
        model = Result
        fields = [
            "waec",
            "subject_1",
            "grade_1",
            "subject_2",
            "grade_2",
            "subject_3",
            "grade_3",
            "subject_4",
            "grade_4",
            "subject_5",
            "grade_5",
            "subject_6",
            "grade_6",
            "subject_7",
            "grade_7",
            "subject_8",
            "grade_8",
            "subject_9",
            "grade_9",
        ]
        widgets = {"waec": forms.HiddenInput()}

core/views.py
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    RedirectView,
    UpdateView,
    DeleteView,
    FormView,
)
from extra_views import CreateWithInlinesView, InlineFormSetFactory

from core.models import Application, Course, AdmissionPeriod, WAEC
from core.forms import (
    AdmissionPeriodCreateForm,
    ApplicationCreateForm,
    WAECCreateForm,
    JAMBCreateForm,
    ResultCreateForm,
    StatusForm,
)


class HomeView(TemplateView):
    template_name = "core/index.html"


class ApplyFirstCreateView(CreateView):
    form_class = ApplicationCreateForm
    template_name = "core/apply/page1.html"

    def get_success_url(self):
        return reverse("core:apply2", kwargs={"ref": self.object.ref})


class ApplySecondCreateView(CreateView):
    form_class = JAMBCreateForm
    template_name = "core/apply/page2.html"

    def get_initial(self):
        appl = get_object_or_404(Application, ref=self.kwargs.get("ref"))
        return {"applicant": appl}

    def get_success_url(self):
        return reverse("core:apply3", kwargs={"ref": self.request.POST["applicant"]})


class ApplyThirdCreateView(CreateView):
    form_class = WAECCreateForm
    template_name = "core/apply/page3.html"

    def get_initial(self):
        appl = get_object_or_404(Application, ref=self.kwargs.get("ref"))
        return {"applicant": appl}

    def get_success_url(self):
        return reverse("core:apply4", kwargs={"res": self.object.id})


class ApplyFourthCreateView(CreateView):
    form_class = ResultCreateForm
    template_name = "core/apply/page4.html"
    success_url = reverse_lazy("core:home")

    def get_initial(self):
        waec = get_object_or_404(WAEC, id=self.kwargs.get("res"))
        return {"waec": waec}


class CheckStatusFormView(FormView):
    form_class = StatusForm
    template_name = "core/status/form.html"

    def get_success_url(self):
        return reverse_lazy(
            "core:admission_status", kwargs={"email": self.request.POST["email"]}
        )


class AdmissionStatusDetailView(DetailView):
    model = Application
    slug_field = "email"
    slug_url_kwarg = "email"
    template_name = "core/status/detail.html"

    def get_queryset(self):
        return Application.objects.filter(email=self.kwargs.get("email"))


class ApplicationListView(LoginRequiredMixin, ListView):
    model = Application
    template_name = "core/list.html"
    context_object_name = "application_forms"


class ApplicationDetailView(DetailView):
    pk_url_kwarg = "ref"
    model = Application
    template_name = "core/detail.html"
    context_object_name = "form"


class StatusRedirectView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy(
            "core:submitted_form", kwargs={"ref": self.request.GET.get("ref")}
        )


class ApplicationAdmitView(LoginRequiredMixin, UpdateView):
    model = Application
    pk_url_kwarg = "ref"
    fields = ["status"]

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy(
            "core:submitted_form", kwargs={"ref": self.kwargs.get("ref")}
        )


class DashboardView(ListView):
    model = Application
    template_name = "core/dashboard/index.html"


class CourseCreateView(LoginRequiredMixin, CreateView):
    model = Course
    template_name = "core/dashboard/course/create.html"
    success_url = reverse_lazy("core:course_list")
    fields = ["title", "faculty"]


class CourseUpdateView(LoginRequiredMixin, UpdateView):
    model = Course
    template_name = "core/dashboard/course/edit.html"
    success_url = reverse_lazy("core:course_list")
    fields = ["title", "faculty"]


class CourseDeleteView(LoginRequiredMixin, DeleteView):
    model = Course
    template_name = "core/dashboard/course/delete.html"
    success_url = reverse_lazy("core:course_list")


class CourseListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = "core/dashboard/course/list.html"


class AdmissionPeriodeCreateView(LoginRequiredMixin, CreateView):
    form_class = AdmissionPeriodCreateForm
    template_name = "core/dashboard/admissions/create.html"
    success_url = reverse_lazy("core:admission_list")

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.staff = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class AdmissionPeriodListView(LoginRequiredMixin, ListView):
    model = AdmissionPeriod
    context_object_name = "admission_period_list"
    template_name = "core/dashboard/admissions/list.html"


class AdmissionPeriodeUpdateView(LoginRequiredMixin, UpdateView):
    form_class = AdmissionPeriodCreateForm
    model = AdmissionPeriod
    template_name = "core/dashboard/admissions/edit.html"
    success_url = reverse_lazy("core:admission_list")


class AdmissionPeriodeDeleteView(LoginRequiredMixin, DeleteView):
    model = AdmissionPeriod
    template_name = "core/dashboard/admissions/delete.html"
    success_url = reverse_lazy("core:admission_list")


class ApplicantListView(LoginRequiredMixin, ListView):
    model = Application
    template_name = "core/dashboard/applicants/list.html"


class ApplicantDetailView(LoginRequiredMixin, UpdateView):
    model = Application
    slug_field = "ref"
    slug_url_kwarg = "ref"
    fields = ["status"]
    template_name = "core/dashboard/applicants/detail.html"
    success_url = reverse_lazy("core:applicant_list")

core/templates/core/dashboard/course/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}



{% block content %}
<!--Main layout-->
<main class="pt-5 mx-lg-5">
    <div class="container-fluid mt-5">

        <!-- Heading -->
        <div class="card mb-4 wow fadeIn">

            <!--Card content-->
            <div class="card-body d-sm-flex justify-content-between">

                <h4 class="mb-2 mb-sm-0 pt-1">
                    <a href="{% url 'core:course_list' %}" target="_blank">Courses</a>
                    <span>/</span>
                    <span>Create</span>
                </h4>



            </div>

        </div>
        <!-- Heading -->
        {% bootstrap_messages %}
        <div class="row wow fadeIn">

            <!--Grid column-->
            <div class="col-md-9 mb-4">

                <!--Card-->
                <div class="card">

                    <!--Card content-->
                    <div class="card-body">

                        <form method="POST" class="form">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            {% buttons %}
                            <button type="submit" class="btn btn-primary">
                                Submit
                            </button>
                            {% endbuttons %}
                        </form>

                    </div>

                </div>
                <!--/.Card-->

            </div>
            <!--Grid column-->
        </div>
    </div>
</main>
<!--Main layout-->
{% endblock content %}

core/templates/core/dashboard/course/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}



{% block content %}
<style>
    .card-columns {
        column-count: 3;
    }
</style>
<!--Main layout-->
<main class="pt-5 mx-lg-5">
    <div class="container-fluid mt-5">


        {% bootstrap_messages %}
        <div class="row wow fadeIn">

            <!--Grid column-->
            <div class="col-md-10 mb-4">


                <div class="alert alert-danger">
                    <form method="post">{% csrf_token %}
                        <p>Are you sure you want to delete "{{ object }}"?</p>
                        <input type="submit" class="btn btn-danger" value="Confirm">
                    </form>
                </div>


            </div>
            <!--Grid column-->
        </div>
    </div>
</main>
<!--Main layout-->
{% endblock content %}

core/templates/core/dashboard/course/edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}



{% block content %}
<!--Main layout-->
<main class="pt-5 mx-lg-5">
    <div class="container-fluid mt-5">

        <!-- Heading -->
        <div class="card mb-4 wow fadeIn">

            <!--Card content-->
            <div class="card-body d-sm-flex justify-content-between">

                <h4 class="mb-2 mb-sm-0 pt-1">
                    <a href="{% url 'core:course_list' %}" target="_blank">Courses</a>
                    <span>/</span>
                    <span>Edit</span>
                </h4>



            </div>

        </div>
        <!-- Heading -->
        {% bootstrap_messages %}
        <div class="row wow fadeIn">

            <!--Grid column-->
            <div class="col-md-9 mb-4">

                <!--Card-->
                <div class="card">

                    <!--Card content-->
                    <div class="card-body">

                        <form method="POST" class="form">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            {% buttons %}
                            <button type="submit" class="btn btn-primary">
                                Submit
                            </button>
                            {% endbuttons %}
                        </form>

                    </div>

                </div>
                <!--/.Card-->

            </div>
            <!--Grid column-->
        </div>
    </div>
</main>
<!--Main layout-->
{% endblock content %}

core/templates/core/dashboard/course/list.html
{% extends 'base.html' %}
{% load bootstrap4 %}



{% block content %}
<style>
    .card-columns {
        column-count: 3;
    }
</style>
<!--Main layout-->
<main class="pt-5 mx-lg-5">
    <div class="container-fluid mt-5">

        <!-- Heading -->
        <div class="card mb-4 wow fadeIn">

            <!--Card content-->
            <div class="card-body d-sm-flex justify-content-between">

                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span>Courses</span>
                </h4>

                <a href="{% url 'core:course_create' %}" class="btn btn-primary">
                    Add Course
                </a>

            </div>

        </div>
        <!-- Heading -->
        {% bootstrap_messages %}
        <div class="row wow fadeIn">

            <!--Grid column-->
            <div class="col-md-10 mb-4">

                <!--Card-->
                <div class="card">

                    <!--Card content-->
                    <div class="card-body">
                        <div class="card-columns">

                            {% for course in course_list %}
                            <div class="card bg-info text-white text-center p-3">
                                <blockquote class="blockquote mb-0">
                                    <p>{{course.title}}</p>
                                    <footer class="blockquote-footer text-white">
                                        <small>
                                            {{course.faculty}}
                                        </small>
                                    </footer>
                                </blockquote>
                                <!--Call to action-->
                                <div class="pt-4 d-flex">
                                    <a class="btn btn-sm btn-primary d-inline-block"
                                        href="{% url 'core:course_edit' course.id %}" role="button">Edit
                                    </a>
                                    <a class="btn btn-sm btn-danger" href="{% url 'core:course_delete' course.id %}"
                                        role="button">
                                        Delete

                                    </a>
                                </div>
                                <!--/.Call to action-->
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <!--/.Card-->

            </div>
            <!--Grid column-->
        </div>
    </div>
</main>
<!--Main layout-->
{% endblock content %}